"""CORE-05 ack/noop/result/error telemetry fixture pack with ordering examples.

Provides realistic fixtures for all four dispatch telemetry payload types
and documents valid/invalid event ordering sequences.

Telemetry Payload Types
=======================
1. dispatch.command  — Manager directs agent to claim a specific task
2. dispatch.ack      — Agent acknowledges command (claim override consumed)
3. dispatch.noop     — Command timed out without ack (claim override stale)
4. worker.result     — Agent delivers task completion result (planned CORE-05)
5. dispatch.error    — Unrecoverable dispatch failure (planned CORE-05)

Valid Ordering Sequences
========================
A) Happy path:   command → ack → result
B) Timeout path:  command → noop  (no ack received within timeout)
C) Ack + failure: command → ack → error  (worker acked but failed)
D) Direct claim:  (no command) → task.claimed  (normal claim without override)

Invalid Ordering (should be flagged by validators):
X1) ack without preceding command  (orphan ack)
X2) result before ack              (result without acknowledgement)
X3) noop after ack                 (noop should be suppressed when ack exists)
X4) duplicate ack for same command (idempotency violation)

Correlation Rules
=================
- All events in a sequence share the same correlation_id (CMD-{hex})
- correlation_id is generated by set_claim_override and threaded through
  claim_next_task (ack) and emit_stale_claim_override_noops (noop)
- task_id must match across all events in the sequence
- source differs: command source=manager, ack source=worker, noop source=manager
"""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from datetime import datetime, timezone

from orchestrator.engine import Orchestrator
from orchestrator.policy import Policy


# ---------------------------------------------------------------------------
# Fixture Definitions
# ---------------------------------------------------------------------------

FIXTURE_COMMAND = {
    "type": "dispatch.command",
    "correlation_id": "CMD-a1b2c3d4e5",
    "command_type": "claim_override",
    "agent": "claude_code",
    "task_id": "TASK-abc12345",
    "source": "codex",
    "timestamp": "2026-02-26T12:00:00+00:00",
}

FIXTURE_ACK = {
    "type": "dispatch.ack",
    "correlation_id": "CMD-a1b2c3d4e5",
    "agent": "claude_code",
    "instance_id": "sess-claude_code",
    "task_id": "TASK-abc12345",
    "ack_type": "claim_override_consumed",
    "source": "claude_code",
    "timestamp": "2026-02-26T12:00:05+00:00",
}

FIXTURE_NOOP = {
    "type": "dispatch.noop",
    "correlation_id": "CMD-a1b2c3d4e5",
    "command_type": "claim_override",
    "agent": "claude_code",
    "task_id": "TASK-abc12345",
    "reason": "claim_override_timeout",
    "age_seconds": 65,
    "source": "codex",
    "timestamp": "2026-02-26T12:01:05+00:00",
}

FIXTURE_RESULT = {
    "type": "worker.result",
    "correlation_id": "CMD-a1b2c3d4e5",
    "task_id": "TASK-abc12345",
    "agent": "claude_code",
    "instance_id": "sess-claude_code",
    "outcome": "success",
    "commit_sha": "abc123def",
    "duration_seconds": 120,
    "source": "claude_code",
    "timestamp": "2026-02-26T12:02:05+00:00",
}

FIXTURE_ERROR = {
    "type": "dispatch.error",
    "correlation_id": "CMD-a1b2c3d4e5",
    "task_id": "TASK-abc12345",
    "agent": "claude_code",
    "error_code": "worker_crash",
    "message": "Worker process exited with non-zero status",
    "source": "claude_code",
    "timestamp": "2026-02-26T12:02:05+00:00",
}

ALL_FIXTURES = {
    "command": FIXTURE_COMMAND,
    "ack": FIXTURE_ACK,
    "noop": FIXTURE_NOOP,
    "result": FIXTURE_RESULT,
    "error": FIXTURE_ERROR,
}

# Valid ordering sequences
VALID_SEQUENCES = {
    "happy_path": ["dispatch.command", "dispatch.ack", "worker.result"],
    "timeout_path": ["dispatch.command", "dispatch.noop"],
    "ack_then_error": ["dispatch.command", "dispatch.ack", "dispatch.error"],
}

# Invalid ordering sequences
INVALID_SEQUENCES = {
    "orphan_ack": ["dispatch.ack"],
    "result_before_ack": ["dispatch.command", "worker.result"],
    "noop_after_ack": ["dispatch.command", "dispatch.ack", "dispatch.noop"],
    "duplicate_ack": ["dispatch.command", "dispatch.ack", "dispatch.ack"],
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_policy(path: Path) -> Policy:
    raw = {
        "name": "test-policy",
        "roles": {"manager": "codex"},
        "routing": {"backend": "claude_code", "frontend": "gemini", "default": "codex"},
        "decisions": {"architecture": {"mode": "consensus", "members": ["codex", "claude_code", "gemini"]}},
        "triggers": {"heartbeat_timeout_minutes": 10, "lease_ttl_seconds": 300},
    }
    path.write_text(json.dumps(raw), encoding="utf-8")
    return Policy.load(path)


def _make_orch(root: Path) -> Orchestrator:
    policy = _make_policy(root / "policy.json")
    orch = Orchestrator(root=root, policy=policy)
    orch.bootstrap()
    return orch


def _full_metadata(root: Path, agent: str) -> dict:
    return {
        "role": "team_member",
        "client": f"{agent}-cli",
        "model": f"{agent}-model",
        "cwd": str(root),
        "project_root": str(root),
        "permissions_mode": "default",
        "sandbox_mode": "workspace-write",
        "session_id": f"sess-{agent}",
        "connection_id": f"conn-{agent}",
        "server_version": "0.1.0",
        "verification_source": "test",
    }


def _setup_agent(orch: Orchestrator, root: Path, agent: str) -> None:
    orch.register_agent(agent, _full_metadata(root, agent))
    orch.heartbeat(agent, _full_metadata(root, agent))


# ---------------------------------------------------------------------------
# 1. Fixture completeness — all payload types have required fields
# ---------------------------------------------------------------------------

class FixtureCompletenessTests(unittest.TestCase):
    """All fixtures must have type, correlation_id, task_id, agent, source, timestamp."""

    COMMON_FIELDS = {"type", "correlation_id", "task_id", "agent", "source", "timestamp"}

    def test_all_fixtures_have_common_fields(self) -> None:
        for name, fixture in ALL_FIXTURES.items():
            for field in self.COMMON_FIELDS:
                self.assertIn(field, fixture, f"fixture '{name}' missing '{field}'")

    def test_command_has_command_type(self) -> None:
        self.assertIn("command_type", FIXTURE_COMMAND)
        self.assertEqual(FIXTURE_COMMAND["command_type"], "claim_override")

    def test_ack_has_ack_type(self) -> None:
        self.assertIn("ack_type", FIXTURE_ACK)
        self.assertEqual(FIXTURE_ACK["ack_type"], "claim_override_consumed")

    def test_ack_has_instance_id(self) -> None:
        self.assertIn("instance_id", FIXTURE_ACK)

    def test_noop_has_reason(self) -> None:
        self.assertIn("reason", FIXTURE_NOOP)
        self.assertEqual(FIXTURE_NOOP["reason"], "claim_override_timeout")

    def test_noop_has_age_seconds(self) -> None:
        self.assertIn("age_seconds", FIXTURE_NOOP)
        self.assertIsInstance(FIXTURE_NOOP["age_seconds"], int)

    def test_result_has_outcome(self) -> None:
        self.assertIn("outcome", FIXTURE_RESULT)
        self.assertIn(FIXTURE_RESULT["outcome"], {"success", "failure"})

    def test_result_has_duration_seconds(self) -> None:
        self.assertIn("duration_seconds", FIXTURE_RESULT)
        self.assertIsInstance(FIXTURE_RESULT["duration_seconds"], (int, float))

    def test_error_has_error_code(self) -> None:
        self.assertIn("error_code", FIXTURE_ERROR)

    def test_error_has_message(self) -> None:
        self.assertIn("message", FIXTURE_ERROR)
        self.assertTrue(len(FIXTURE_ERROR["message"]) > 0)


# ---------------------------------------------------------------------------
# 2. Correlation consistency across fixture pack
# ---------------------------------------------------------------------------

class CorrelationConsistencyTests(unittest.TestCase):
    """All fixtures in the pack share the same correlation_id and task_id."""

    def test_all_share_same_correlation_id(self) -> None:
        cid = FIXTURE_COMMAND["correlation_id"]
        for name, fixture in ALL_FIXTURES.items():
            self.assertEqual(fixture["correlation_id"], cid,
                             f"fixture '{name}' has different correlation_id")

    def test_all_share_same_task_id(self) -> None:
        tid = FIXTURE_COMMAND["task_id"]
        for name, fixture in ALL_FIXTURES.items():
            self.assertEqual(fixture["task_id"], tid,
                             f"fixture '{name}' has different task_id")

    def test_correlation_id_format(self) -> None:
        cid = FIXTURE_COMMAND["correlation_id"]
        self.assertTrue(cid.startswith("CMD-"), "correlation_id should start with CMD-")

    def test_timestamps_are_valid_iso8601(self) -> None:
        for name, fixture in ALL_FIXTURES.items():
            try:
                datetime.fromisoformat(fixture["timestamp"])
            except ValueError:
                self.fail(f"fixture '{name}' has invalid timestamp")

    def test_timestamps_are_chronological(self) -> None:
        """command < ack < result (happy path ordering by timestamp)."""
        cmd_ts = datetime.fromisoformat(FIXTURE_COMMAND["timestamp"])
        ack_ts = datetime.fromisoformat(FIXTURE_ACK["timestamp"])
        result_ts = datetime.fromisoformat(FIXTURE_RESULT["timestamp"])
        self.assertLess(cmd_ts, ack_ts)
        self.assertLess(ack_ts, result_ts)


# ---------------------------------------------------------------------------
# 3. Source attribution rules
# ---------------------------------------------------------------------------

class SourceAttributionTests(unittest.TestCase):
    """Correct source attribution per event type."""

    def test_command_source_is_manager(self) -> None:
        self.assertEqual(FIXTURE_COMMAND["source"], "codex")

    def test_ack_source_is_worker(self) -> None:
        self.assertEqual(FIXTURE_ACK["source"], "claude_code")

    def test_noop_source_is_manager(self) -> None:
        self.assertEqual(FIXTURE_NOOP["source"], "codex")

    def test_result_source_is_worker(self) -> None:
        self.assertEqual(FIXTURE_RESULT["source"], "claude_code")

    def test_error_source_is_worker(self) -> None:
        self.assertEqual(FIXTURE_ERROR["source"], "claude_code")


# ---------------------------------------------------------------------------
# 4. Valid ordering sequence validation
# ---------------------------------------------------------------------------

class ValidOrderingTests(unittest.TestCase):
    """Valid sequences should follow defined ordering rules."""

    def test_happy_path_starts_with_command(self) -> None:
        self.assertEqual(VALID_SEQUENCES["happy_path"][0], "dispatch.command")

    def test_happy_path_ends_with_result(self) -> None:
        self.assertEqual(VALID_SEQUENCES["happy_path"][-1], "worker.result")

    def test_timeout_path_has_no_ack(self) -> None:
        self.assertNotIn("dispatch.ack", VALID_SEQUENCES["timeout_path"])

    def test_timeout_path_ends_with_noop(self) -> None:
        self.assertEqual(VALID_SEQUENCES["timeout_path"][-1], "dispatch.noop")

    def test_ack_then_error_has_ack_before_error(self) -> None:
        seq = VALID_SEQUENCES["ack_then_error"]
        self.assertLess(seq.index("dispatch.ack"), seq.index("dispatch.error"))

    def test_all_valid_sequences_start_with_command(self) -> None:
        for name, seq in VALID_SEQUENCES.items():
            self.assertEqual(seq[0], "dispatch.command",
                             f"valid sequence '{name}' must start with command")


# ---------------------------------------------------------------------------
# 5. Invalid ordering detection
# ---------------------------------------------------------------------------

class InvalidOrderingTests(unittest.TestCase):
    """Invalid sequences document violations that validators should catch."""

    def test_orphan_ack_has_no_command(self) -> None:
        seq = INVALID_SEQUENCES["orphan_ack"]
        self.assertNotIn("dispatch.command", seq)

    def test_result_before_ack_is_out_of_order(self) -> None:
        seq = INVALID_SEQUENCES["result_before_ack"]
        self.assertNotIn("dispatch.ack", seq)

    def test_noop_after_ack_is_contradictory(self) -> None:
        """Noop should not follow ack — ack means command was consumed."""
        seq = INVALID_SEQUENCES["noop_after_ack"]
        self.assertIn("dispatch.ack", seq)
        self.assertIn("dispatch.noop", seq)

    def test_duplicate_ack_has_two_acks(self) -> None:
        seq = INVALID_SEQUENCES["duplicate_ack"]
        self.assertEqual(seq.count("dispatch.ack"), 2)

    def test_invalid_sequences_are_distinct_from_valid(self) -> None:
        valid_set = set(tuple(s) for s in VALID_SEQUENCES.values())
        for name, seq in INVALID_SEQUENCES.items():
            self.assertNotIn(tuple(seq), valid_set,
                             f"invalid sequence '{name}' should not match any valid sequence")


# ---------------------------------------------------------------------------
# 6. Live telemetry — command + ack integration
# ---------------------------------------------------------------------------

class LiveCommandAckIntegrationTests(unittest.TestCase):
    """Live command→ack telemetry via set_claim_override + claim_next_task."""

    def test_command_event_emitted_on_override(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            orch = _make_orch(root)
            _setup_agent(orch, root, "claude_code")
            task = orch.create_task(
                title="Live cmd test",
                workstream="backend",
                owner="claude_code",
                acceptance_criteria=["test"],
            )
            orch.bus.events_path.write_text("", encoding="utf-8")

            orch.set_claim_override(agent="claude_code", task_id=task["id"], source="codex")

            events = list(orch.bus.iter_events())
            cmd_events = [e for e in events if e.get("type") == "dispatch.command"]
            self.assertEqual(len(cmd_events), 1)
            self.assertEqual(cmd_events[0]["payload"]["command_type"], "claim_override")

    def test_ack_event_emitted_on_claim(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            orch = _make_orch(root)
            _setup_agent(orch, root, "claude_code")
            task = orch.create_task(
                title="Live ack test",
                workstream="backend",
                owner="claude_code",
                acceptance_criteria=["test"],
            )
            override = orch.set_claim_override(
                agent="claude_code", task_id=task["id"], source="codex",
            )
            orch.bus.events_path.write_text("", encoding="utf-8")

            orch.claim_next_task("claude_code")

            events = list(orch.bus.iter_events())
            ack_events = [e for e in events if e.get("type") == "dispatch.ack"]
            self.assertEqual(len(ack_events), 1)
            self.assertEqual(ack_events[0]["payload"]["ack_type"], "claim_override_consumed")

    def test_command_and_ack_share_correlation_id(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            orch = _make_orch(root)
            _setup_agent(orch, root, "claude_code")
            task = orch.create_task(
                title="Live corr test",
                workstream="backend",
                owner="claude_code",
                acceptance_criteria=["test"],
            )
            orch.bus.events_path.write_text("", encoding="utf-8")

            override = orch.set_claim_override(
                agent="claude_code", task_id=task["id"], source="codex",
            )
            orch.claim_next_task("claude_code")

            events = list(orch.bus.iter_events())
            cmd = next(e for e in events if e.get("type") == "dispatch.command")
            ack = next(e for e in events if e.get("type") == "dispatch.ack")
            self.assertEqual(cmd["payload"]["correlation_id"], ack["payload"]["correlation_id"])

    def test_noop_emitted_on_stale_override(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            orch = _make_orch(root)
            _setup_agent(orch, root, "claude_code")
            task = orch.create_task(
                title="Live noop test",
                workstream="backend",
                owner="claude_code",
                acceptance_criteria=["test"],
            )
            orch.set_claim_override(
                agent="claude_code", task_id=task["id"], source="codex",
            )
            # Backdate override to trigger timeout
            overrides = orch._read_json(orch.claim_overrides_path)
            overrides["claude_code"]["created_at"] = "2020-01-01T00:00:00+00:00"
            orch._write_json(orch.claim_overrides_path, overrides)
            orch.bus.events_path.write_text("", encoding="utf-8")

            orch.emit_stale_claim_override_noops(source="codex", timeout_seconds=5)

            events = list(orch.bus.iter_events())
            noop_events = [e for e in events if e.get("type") == "dispatch.noop"]
            self.assertEqual(len(noop_events), 1)
            self.assertEqual(noop_events[0]["payload"]["reason"], "claim_override_timeout")


if __name__ == "__main__":
    unittest.main()
